### ISSUE TITLE
Getting this to work in the browser

### ISSUE THREAD

**Issue by alexbjorlig** [erikwett/helpdesk-angular#1]
Hi Erik - and thanks for the code. 

When I use the Qlik Sense editor the code works, but when trying to access the mashup in the browser using an URL , nothing happens? The console just prints the following: 

Failed to load resource: the server responded with a status of 404 (Not Found)

And I try with this url:
http://localhost:4848/extensions/helpdesk-angular-master/helpdesk-angular.html

**Comment by erikwett** [comment]
Try with:
http://localhost:4848/extensions/helpdesk-angular/helpdesk-angular.html

The path after extensions should be the qext filename.
