### ISSUE TITLE
Error with Uncaught Error: Script error for: js/qlik

### ISSUE THREAD

**Issue by danielriosb** [erikwett/helpdesk-angular#2]
I trying to run your app but Im getting the follow error:

> Uncaught Error: Script error for: js/qlik

I have Qlik sense in the same box as this app.
I would appreciate your help

**Comment by ansarikhurshid786** [comment]
I also have same problem. @danielriosb have you got solution?

**Comment by erikwett** [comment]
Cannot reproduce this in desktop, and hard to know your problem with so little information. Desktop or server? Virtual proxy??? Qlik Sense version?? There was however links in the file that might not work in a virtual proxy configuration. I have fixed thos.

**Comment by ansarikhurshid786** [comment]
Yes you are right. I have solve this problem. There is way to get solution.

There is problem in your config(host, port). Try to copy url of qlik/js and paste it in new tab. If you can see that file is available or not else try to modify url as per back end developer....
